spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/petdb
spring.datasource.username=root
spring.datasource.password=123qwe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
