spring.application.name=auth-service

#Prometheus
management.endpoints.web.exposure.include=health,info, prometheus



# DB SETTINGS
spring.datasource.url=jdbc:postgresql://localhost:5432/petdb
spring.datasource.username=root
spring.datasource.password=123qwe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#JWT SETTINGS
jwt.secret=kewkmwgmpogrqrkvgpokqebpoerbkam12n34oimwvpdsf233gqbrivf324g03btwrgwgq34wtb